@echo off
echo Iniciando serviços...
docker-compose -f docker/docker-compose.yml up -d

echo Aguardando serviços estarem prontos...
timeout /t 10

echo Verificando status...
docker-compose -f docker/docker-compose.yml ps

echo Iniciando aplicação...
mvn spring-boot:run
